/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { FactoryLike, FactoryLikeInterface } from "../FactoryLike";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "",
        type: "address",
      },
    ],
    name: "poolExist",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class FactoryLike__factory {
  static readonly abi = _abi;
  static createInterface(): FactoryLikeInterface {
    return new utils.Interface(_abi) as FactoryLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FactoryLike {
    return new Contract(address, _abi, signerOrProvider) as FactoryLike;
  }
}
