/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IKLAYSwap, IKLAYSwapInterface } from "../IKLAYSwap";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "token",
        type: "address",
      },
      {
        name: "amount",
        type: "uint256",
      },
      {
        name: "path",
        type: "address[]",
      },
    ],
    name: "exchangeKlayPos",
    outputs: [],
    payable: true,
    stateMutability: "payable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "tokenA",
        type: "address",
      },
      {
        name: "amountA",
        type: "uint256",
      },
      {
        name: "tokenB",
        type: "address",
      },
      {
        name: "amountB",
        type: "uint256",
      },
      {
        name: "path",
        type: "address[]",
      },
    ],
    name: "exchangeKctPos",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKLAYSwap__factory {
  static readonly abi = _abi;
  static createInterface(): IKLAYSwapInterface {
    return new utils.Interface(_abi) as IKLAYSwapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKLAYSwap {
    return new Contract(address, _abi, signerOrProvider) as IKLAYSwap;
  }
}
