/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IMixEmitter, IMixEmitterInterface } from "../IMixEmitter";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "pid",
        type: "uint256",
      },
    ],
    name: "poolInfo",
    outputs: [
      {
        name: "to",
        type: "address",
      },
      {
        name: "allocPoint",
        type: "uint256",
      },
      {
        name: "lastEmitBlock",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "totalAllocPoint",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "started",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "pid",
        type: "uint256",
      },
    ],
    name: "updatePool",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "mix",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "pid",
        type: "uint256",
      },
    ],
    name: "pendingMix",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "emissionPerBlock",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "poolCount",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        name: "allocPoint",
        type: "uint256",
      },
    ],
    name: "Add",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "pid",
        type: "uint256",
      },
      {
        indexed: false,
        name: "allocPoint",
        type: "uint256",
      },
    ],
    name: "Set",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "emissionPerBlock",
        type: "uint256",
      },
    ],
    name: "SetEmissionPerBlock",
    type: "event",
  },
];

export class IMixEmitter__factory {
  static readonly abi = _abi;
  static createInterface(): IMixEmitterInterface {
    return new utils.Interface(_abi) as IMixEmitterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMixEmitter {
    return new Contract(address, _abi, signerOrProvider) as IMixEmitter;
  }
}
