/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IPFPStoreV2Interface extends ethers.utils.Interface {
  functions: {
    "batchTransfer(address[],uint256[],address[])": FunctionFragment;
    "userAuctionInfoLength(address)": FunctionFragment;
    "cancelOffer(address,uint256,uint256)": FunctionFragment;
    "bid(address,uint256,uint256)": FunctionFragment;
    "onSalesCount(address)": FunctionFragment;
    "userAuctionInfo(address,uint256)": FunctionFragment;
    "offerCount(address,uint256)": FunctionFragment;
    "sales(address,uint256)": FunctionFragment;
    "userBiddingInfoLength(address)": FunctionFragment;
    "acceptOffer(address,uint256,uint256)": FunctionFragment;
    "auctions(address,uint256)": FunctionFragment;
    "biddings(address,uint256,uint256)": FunctionFragment;
    "userOfferInfo(address,uint256)": FunctionFragment;
    "userSellInfoLength(address)": FunctionFragment;
    "createAuction(address,uint256,uint256,uint256)": FunctionFragment;
    "makeOffer(address,uint256,uint256)": FunctionFragment;
    "onAuctions(address,uint256)": FunctionFragment;
    "cancelAuction(address,uint256)": FunctionFragment;
    "biddingCount(address,uint256)": FunctionFragment;
    "checkAuction(address,uint256)": FunctionFragment;
    "isBanned(address)": FunctionFragment;
    "userOfferInfoLength(address)": FunctionFragment;
    "sell(address[],uint256[],uint256[])": FunctionFragment;
    "auctionExtensionInterval()": FunctionFragment;
    "claim(address,uint256)": FunctionFragment;
    "cancelSale(address[],uint256[])": FunctionFragment;
    "changeSellPrice(address[],uint256[],uint256[])": FunctionFragment;
    "userSellInfo(address,uint256)": FunctionFragment;
    "onAuctionsCount(address)": FunctionFragment;
    "onSales(address,uint256)": FunctionFragment;
    "buy(address[],uint256[])": FunctionFragment;
    "userBiddingInfo(address,uint256)": FunctionFragment;
    "offers(address,uint256,uint256)": FunctionFragment;
    "checkSelling(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "batchTransfer",
    values: [string[], BigNumberish[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "userAuctionInfoLength",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOffer",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bid",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onSalesCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userAuctionInfo",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "offerCount",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sales",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userBiddingInfoLength",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOffer",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "auctions",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "biddings",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userOfferInfo",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userSellInfoLength",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "makeOffer",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onAuctions",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAuction",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "biddingCount",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAuction",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isBanned", values: [string]): string;
  encodeFunctionData(
    functionFragment: "userOfferInfoLength",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [string[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "auctionExtensionInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSale",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "changeSellPrice",
    values: [string[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "userSellInfo",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onAuctionsCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "onSales",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "userBiddingInfo",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "offers",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkSelling",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userAuctionInfoLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onSalesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userAuctionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "offerCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sales", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userBiddingInfoLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "biddings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userOfferInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userSellInfoLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "makeOffer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onAuctions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "biddingCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isBanned", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userOfferInfoLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "auctionExtensionInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelSale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userSellInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onAuctionsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onSales", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userBiddingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "offers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkSelling",
    data: BytesLike
  ): Result;

  events: {
    "Sell(address,uint256,address,uint256)": EventFragment;
    "ChangeSellPrice(address,uint256,address,uint256)": EventFragment;
    "Buy(address,uint256,address,uint256)": EventFragment;
    "CancelSale(address,uint256,address)": EventFragment;
    "MakeOffer(address,uint256,uint256,address,uint256)": EventFragment;
    "CancelOffer(address,uint256,uint256,address)": EventFragment;
    "AcceptOffer(address,uint256,uint256,address)": EventFragment;
    "CreateAuction(address,uint256,address,uint256,uint256)": EventFragment;
    "CancelAuction(address,uint256,address)": EventFragment;
    "Bid(address,uint256,address,uint256)": EventFragment;
    "Claim(address,uint256,address,uint256)": EventFragment;
    "CancelSaleByOwner(address,uint256)": EventFragment;
    "CancelOfferByOwner(address,uint256,uint256)": EventFragment;
    "CancelAuctionByOwner(address,uint256)": EventFragment;
    "Ban(address)": EventFragment;
    "Unban(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Sell"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChangeSellPrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Buy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelSale"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MakeOffer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelOffer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AcceptOffer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreateAuction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelAuction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Bid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelSaleByOwner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelOfferByOwner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelAuctionByOwner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Ban"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unban"): EventFragment;
}

export class IPFPStoreV2 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IPFPStoreV2Interface;

  functions: {
    batchTransfer(
      addrs: string[],
      ids: BigNumberish[],
      to: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "batchTransfer(address[],uint256[],address[])"(
      addrs: string[],
      ids: BigNumberish[],
      to: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    userAuctionInfoLength(
      seller: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "userAuctionInfoLength(address)"(
      seller: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    cancelOffer(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelOffer(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    bid(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "bid(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    onSalesCount(addr: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "onSalesCount(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    userAuctionInfo(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        startPrice: BigNumber;
      }
    >;

    "userAuctionInfo(address,uint256)"(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        startPrice: BigNumber;
      }
    >;

    offerCount(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "offerCount(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    sales(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { seller: string; price: BigNumber }>;

    "sales(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { seller: string; price: BigNumber }>;

    userBiddingInfoLength(
      bidder: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "userBiddingInfoLength(address)"(
      bidder: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    acceptOffer(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "acceptOffer(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    auctions(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        seller: string;
        startPrice: BigNumber;
        endBlock: BigNumber;
      }
    >;

    "auctions(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        seller: string;
        startPrice: BigNumber;
        endBlock: BigNumber;
      }
    >;

    biddings(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { bidder: string; price: BigNumber }>;

    "biddings(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { bidder: string; price: BigNumber }>;

    userOfferInfo(
      offeror: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        price: BigNumber;
      }
    >;

    "userOfferInfo(address,uint256)"(
      offeror: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        price: BigNumber;
      }
    >;

    userSellInfoLength(
      seller: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "userSellInfoLength(address)"(
      seller: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    createAuction(
      addr: string,
      id: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createAuction(address,uint256,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    makeOffer(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "makeOffer(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    onAuctions(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "onAuctions(address,uint256)"(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    cancelAuction(
      addr: string,
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelAuction(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    biddingCount(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "biddingCount(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    checkAuction(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "checkAuction(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isBanned(user: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isBanned(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    userOfferInfoLength(
      offeror: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "userOfferInfoLength(address)"(
      offeror: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    sell(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sell(address[],uint256[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    auctionExtensionInterval(overrides?: CallOverrides): Promise<[BigNumber]>;

    "auctionExtensionInterval()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    claim(
      addr: string,
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claim(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    cancelSale(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelSale(address[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    changeSellPrice(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changeSellPrice(address[],uint256[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    userSellInfo(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        price: BigNumber;
      }
    >;

    "userSellInfo(address,uint256)"(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        price: BigNumber;
      }
    >;

    onAuctionsCount(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "onAuctionsCount(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    onSales(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "onSales(address,uint256)"(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    buy(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "buy(address[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    userBiddingInfo(
      bidder: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        price: BigNumber;
      }
    >;

    "userBiddingInfo(address,uint256)"(
      bidder: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        price: BigNumber;
      }
    >;

    offers(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { offeror: string; price: BigNumber }>;

    "offers(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { offeror: string; price: BigNumber }>;

    checkSelling(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "checkSelling(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  batchTransfer(
    addrs: string[],
    ids: BigNumberish[],
    to: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "batchTransfer(address[],uint256[],address[])"(
    addrs: string[],
    ids: BigNumberish[],
    to: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  userAuctionInfoLength(
    seller: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "userAuctionInfoLength(address)"(
    seller: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  cancelOffer(
    addr: string,
    id: BigNumberish,
    offerId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cancelOffer(address,uint256,uint256)"(
    addr: string,
    id: BigNumberish,
    offerId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  bid(
    addr: string,
    id: BigNumberish,
    price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "bid(address,uint256,uint256)"(
    addr: string,
    id: BigNumberish,
    price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  onSalesCount(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

  "onSalesCount(address)"(
    addr: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  userAuctionInfo(
    seller: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      pfp: string;
      id: BigNumber;
      startPrice: BigNumber;
    }
  >;

  "userAuctionInfo(address,uint256)"(
    seller: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      pfp: string;
      id: BigNumber;
      startPrice: BigNumber;
    }
  >;

  offerCount(
    addr: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "offerCount(address,uint256)"(
    addr: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  sales(
    addr: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { seller: string; price: BigNumber }>;

  "sales(address,uint256)"(
    addr: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { seller: string; price: BigNumber }>;

  userBiddingInfoLength(
    bidder: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "userBiddingInfoLength(address)"(
    bidder: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  acceptOffer(
    addr: string,
    id: BigNumberish,
    offerId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "acceptOffer(address,uint256,uint256)"(
    addr: string,
    id: BigNumberish,
    offerId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  auctions(
    addr: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      seller: string;
      startPrice: BigNumber;
      endBlock: BigNumber;
    }
  >;

  "auctions(address,uint256)"(
    addr: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      seller: string;
      startPrice: BigNumber;
      endBlock: BigNumber;
    }
  >;

  biddings(
    addr: string,
    id: BigNumberish,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { bidder: string; price: BigNumber }>;

  "biddings(address,uint256,uint256)"(
    addr: string,
    id: BigNumberish,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { bidder: string; price: BigNumber }>;

  userOfferInfo(
    offeror: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      pfp: string;
      id: BigNumber;
      price: BigNumber;
    }
  >;

  "userOfferInfo(address,uint256)"(
    offeror: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      pfp: string;
      id: BigNumber;
      price: BigNumber;
    }
  >;

  userSellInfoLength(
    seller: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "userSellInfoLength(address)"(
    seller: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  createAuction(
    addr: string,
    id: BigNumberish,
    startPrice: BigNumberish,
    endBlock: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createAuction(address,uint256,uint256,uint256)"(
    addr: string,
    id: BigNumberish,
    startPrice: BigNumberish,
    endBlock: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  makeOffer(
    addr: string,
    id: BigNumberish,
    price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "makeOffer(address,uint256,uint256)"(
    addr: string,
    id: BigNumberish,
    price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  onAuctions(
    addr: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "onAuctions(address,uint256)"(
    addr: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  cancelAuction(
    addr: string,
    id: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cancelAuction(address,uint256)"(
    addr: string,
    id: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  biddingCount(
    addr: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "biddingCount(address,uint256)"(
    addr: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  checkAuction(
    addr: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "checkAuction(address,uint256)"(
    addr: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isBanned(user: string, overrides?: CallOverrides): Promise<boolean>;

  "isBanned(address)"(
    user: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  userOfferInfoLength(
    offeror: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "userOfferInfoLength(address)"(
    offeror: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  sell(
    addrs: string[],
    ids: BigNumberish[],
    prices: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sell(address[],uint256[],uint256[])"(
    addrs: string[],
    ids: BigNumberish[],
    prices: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  auctionExtensionInterval(overrides?: CallOverrides): Promise<BigNumber>;

  "auctionExtensionInterval()"(overrides?: CallOverrides): Promise<BigNumber>;

  claim(
    addr: string,
    id: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claim(address,uint256)"(
    addr: string,
    id: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  cancelSale(
    addrs: string[],
    ids: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cancelSale(address[],uint256[])"(
    addrs: string[],
    ids: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  changeSellPrice(
    addrs: string[],
    ids: BigNumberish[],
    prices: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changeSellPrice(address[],uint256[],uint256[])"(
    addrs: string[],
    ids: BigNumberish[],
    prices: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  userSellInfo(
    seller: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      pfp: string;
      id: BigNumber;
      price: BigNumber;
    }
  >;

  "userSellInfo(address,uint256)"(
    seller: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      pfp: string;
      id: BigNumber;
      price: BigNumber;
    }
  >;

  onAuctionsCount(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

  "onAuctionsCount(address)"(
    addr: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  onSales(
    addr: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "onSales(address,uint256)"(
    addr: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  buy(
    addrs: string[],
    ids: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "buy(address[],uint256[])"(
    addrs: string[],
    ids: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  userBiddingInfo(
    bidder: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      pfp: string;
      id: BigNumber;
      price: BigNumber;
    }
  >;

  "userBiddingInfo(address,uint256)"(
    bidder: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      pfp: string;
      id: BigNumber;
      price: BigNumber;
    }
  >;

  offers(
    addr: string,
    id: BigNumberish,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { offeror: string; price: BigNumber }>;

  "offers(address,uint256,uint256)"(
    addr: string,
    id: BigNumberish,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { offeror: string; price: BigNumber }>;

  checkSelling(
    addr: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "checkSelling(address,uint256)"(
    addr: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    batchTransfer(
      addrs: string[],
      ids: BigNumberish[],
      to: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "batchTransfer(address[],uint256[],address[])"(
      addrs: string[],
      ids: BigNumberish[],
      to: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    userAuctionInfoLength(
      seller: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userAuctionInfoLength(address)"(
      seller: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelOffer(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelOffer(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    bid(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "bid(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onSalesCount(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    "onSalesCount(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userAuctionInfo(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        startPrice: BigNumber;
      }
    >;

    "userAuctionInfo(address,uint256)"(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        startPrice: BigNumber;
      }
    >;

    offerCount(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "offerCount(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sales(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { seller: string; price: BigNumber }>;

    "sales(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { seller: string; price: BigNumber }>;

    userBiddingInfoLength(
      bidder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userBiddingInfoLength(address)"(
      bidder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    acceptOffer(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "acceptOffer(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    auctions(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        seller: string;
        startPrice: BigNumber;
        endBlock: BigNumber;
      }
    >;

    "auctions(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        seller: string;
        startPrice: BigNumber;
        endBlock: BigNumber;
      }
    >;

    biddings(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { bidder: string; price: BigNumber }>;

    "biddings(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { bidder: string; price: BigNumber }>;

    userOfferInfo(
      offeror: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        price: BigNumber;
      }
    >;

    "userOfferInfo(address,uint256)"(
      offeror: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        price: BigNumber;
      }
    >;

    userSellInfoLength(
      seller: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userSellInfoLength(address)"(
      seller: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createAuction(
      addr: string,
      id: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createAuction(address,uint256,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    makeOffer(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "makeOffer(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onAuctions(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "onAuctions(address,uint256)"(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelAuction(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelAuction(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    biddingCount(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "biddingCount(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkAuction(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "checkAuction(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isBanned(user: string, overrides?: CallOverrides): Promise<boolean>;

    "isBanned(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    userOfferInfoLength(
      offeror: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userOfferInfoLength(address)"(
      offeror: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sell(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "sell(address[],uint256[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    auctionExtensionInterval(overrides?: CallOverrides): Promise<BigNumber>;

    "auctionExtensionInterval()"(overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "claim(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelSale(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelSale(address[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    changeSellPrice(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "changeSellPrice(address[],uint256[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    userSellInfo(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        price: BigNumber;
      }
    >;

    "userSellInfo(address,uint256)"(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        price: BigNumber;
      }
    >;

    onAuctionsCount(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "onAuctionsCount(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onSales(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "onSales(address,uint256)"(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buy(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "buy(address[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    userBiddingInfo(
      bidder: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        price: BigNumber;
      }
    >;

    "userBiddingInfo(address,uint256)"(
      bidder: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        pfp: string;
        id: BigNumber;
        price: BigNumber;
      }
    >;

    offers(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { offeror: string; price: BigNumber }>;

    "offers(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { offeror: string; price: BigNumber }>;

    checkSelling(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "checkSelling(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    Sell(
      addr: string | null,
      id: BigNumberish | null,
      owner: string | null,
      price: null
    ): EventFilter;

    ChangeSellPrice(
      addr: string | null,
      id: BigNumberish | null,
      owner: string | null,
      price: null
    ): EventFilter;

    Buy(
      addr: string | null,
      id: BigNumberish | null,
      buyer: string | null,
      price: null
    ): EventFilter;

    CancelSale(
      addr: string | null,
      id: BigNumberish | null,
      owner: string | null
    ): EventFilter;

    MakeOffer(
      addr: string | null,
      id: BigNumberish | null,
      offerId: BigNumberish | null,
      offeror: null,
      price: null
    ): EventFilter;

    CancelOffer(
      addr: string | null,
      id: BigNumberish | null,
      offerId: BigNumberish | null,
      offeror: null
    ): EventFilter;

    AcceptOffer(
      addr: string | null,
      id: BigNumberish | null,
      offerId: BigNumberish | null,
      acceptor: null
    ): EventFilter;

    CreateAuction(
      addr: string | null,
      id: BigNumberish | null,
      owner: string | null,
      startPrice: null,
      endBlock: null
    ): EventFilter;

    CancelAuction(
      addr: string | null,
      id: BigNumberish | null,
      owner: string | null
    ): EventFilter;

    Bid(
      addr: string | null,
      id: BigNumberish | null,
      bidder: string | null,
      price: null
    ): EventFilter;

    Claim(
      addr: string | null,
      id: BigNumberish | null,
      bidder: string | null,
      price: null
    ): EventFilter;

    CancelSaleByOwner(
      addr: string | null,
      id: BigNumberish | null
    ): EventFilter;

    CancelOfferByOwner(
      addr: string | null,
      id: BigNumberish | null,
      offerId: BigNumberish | null
    ): EventFilter;

    CancelAuctionByOwner(
      addr: string | null,
      id: BigNumberish | null
    ): EventFilter;

    Ban(user: string | null): EventFilter;

    Unban(user: string | null): EventFilter;
  };

  estimateGas: {
    batchTransfer(
      addrs: string[],
      ids: BigNumberish[],
      to: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "batchTransfer(address[],uint256[],address[])"(
      addrs: string[],
      ids: BigNumberish[],
      to: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    userAuctionInfoLength(
      seller: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userAuctionInfoLength(address)"(
      seller: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelOffer(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "cancelOffer(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    bid(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "bid(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    onSalesCount(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    "onSalesCount(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userAuctionInfo(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userAuctionInfo(address,uint256)"(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    offerCount(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "offerCount(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sales(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sales(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userBiddingInfoLength(
      bidder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userBiddingInfoLength(address)"(
      bidder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    acceptOffer(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "acceptOffer(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    auctions(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "auctions(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    biddings(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "biddings(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userOfferInfo(
      offeror: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userOfferInfo(address,uint256)"(
      offeror: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userSellInfoLength(
      seller: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userSellInfoLength(address)"(
      seller: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createAuction(
      addr: string,
      id: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createAuction(address,uint256,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    makeOffer(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "makeOffer(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    onAuctions(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "onAuctions(address,uint256)"(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelAuction(
      addr: string,
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "cancelAuction(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    biddingCount(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "biddingCount(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkAuction(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkAuction(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isBanned(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isBanned(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userOfferInfoLength(
      offeror: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userOfferInfoLength(address)"(
      offeror: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sell(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sell(address[],uint256[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    auctionExtensionInterval(overrides?: CallOverrides): Promise<BigNumber>;

    "auctionExtensionInterval()"(overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      addr: string,
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claim(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    cancelSale(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "cancelSale(address[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    changeSellPrice(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "changeSellPrice(address[],uint256[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    userSellInfo(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userSellInfo(address,uint256)"(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onAuctionsCount(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "onAuctionsCount(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onSales(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "onSales(address,uint256)"(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buy(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "buy(address[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    userBiddingInfo(
      bidder: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userBiddingInfo(address,uint256)"(
      bidder: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    offers(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "offers(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkSelling(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkSelling(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchTransfer(
      addrs: string[],
      ids: BigNumberish[],
      to: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "batchTransfer(address[],uint256[],address[])"(
      addrs: string[],
      ids: BigNumberish[],
      to: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    userAuctionInfoLength(
      seller: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "userAuctionInfoLength(address)"(
      seller: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelOffer(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelOffer(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    bid(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "bid(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    onSalesCount(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "onSalesCount(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userAuctionInfo(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "userAuctionInfo(address,uint256)"(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    offerCount(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "offerCount(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sales(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "sales(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userBiddingInfoLength(
      bidder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "userBiddingInfoLength(address)"(
      bidder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    acceptOffer(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "acceptOffer(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    auctions(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "auctions(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    biddings(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "biddings(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userOfferInfo(
      offeror: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "userOfferInfo(address,uint256)"(
      offeror: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userSellInfoLength(
      seller: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "userSellInfoLength(address)"(
      seller: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createAuction(
      addr: string,
      id: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createAuction(address,uint256,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    makeOffer(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "makeOffer(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    onAuctions(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "onAuctions(address,uint256)"(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelAuction(
      addr: string,
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelAuction(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    biddingCount(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "biddingCount(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkAuction(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkAuction(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isBanned(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isBanned(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userOfferInfoLength(
      offeror: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "userOfferInfoLength(address)"(
      offeror: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sell(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sell(address[],uint256[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    auctionExtensionInterval(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "auctionExtensionInterval()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(
      addr: string,
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claim(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    cancelSale(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelSale(address[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    changeSellPrice(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changeSellPrice(address[],uint256[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      prices: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    userSellInfo(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "userSellInfo(address,uint256)"(
      seller: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onAuctionsCount(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "onAuctionsCount(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onSales(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "onSales(address,uint256)"(
      addr: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buy(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "buy(address[],uint256[])"(
      addrs: string[],
      ids: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    userBiddingInfo(
      bidder: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "userBiddingInfo(address,uint256)"(
      bidder: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    offers(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "offers(address,uint256,uint256)"(
      addr: string,
      id: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkSelling(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkSelling(address,uint256)"(
      addr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
