/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IItemStoreAuction } from "../IItemStoreAuction";

export class IItemStoreAuction__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IItemStoreAuction {
    return new Contract(address, _abi, signerOrProvider) as IItemStoreAuction;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "seller",
        type: "address",
      },
    ],
    name: "userAuctionInfoLength",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "metaverseId",
        type: "uint256",
      },
    ],
    name: "auctionsOnMetaverseLength",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "auctionVerificationID",
        type: "bytes32",
      },
      {
        name: "biddingId",
        type: "uint256",
      },
    ],
    name: "biddings",
    outputs: [
      {
        name: "bidder",
        type: "address",
      },
      {
        name: "metaverseId",
        type: "uint256",
      },
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
      },
      {
        name: "price",
        type: "uint256",
      },
      {
        name: "mileage",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "seller",
        type: "address",
      },
      {
        name: "index",
        type: "uint256",
      },
    ],
    name: "userAuctionInfo",
    outputs: [
      {
        name: "auctionVerificationID",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "metaverseId",
        type: "uint256",
      },
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
      },
      {
        name: "startTotalPrice",
        type: "uint256",
      },
      {
        name: "endBlock",
        type: "uint256",
      },
    ],
    name: "createAuction",
    outputs: [
      {
        name: "auctionId",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "bidder",
        type: "address",
      },
    ],
    name: "userBiddingInfoLength",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "auctionVerificationID",
        type: "bytes32",
      },
    ],
    name: "cancelAuction",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "auctionVerificationID",
        type: "bytes32",
      },
    ],
    name: "biddingsCount",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "auctionVerificationID",
        type: "bytes32",
      },
      {
        name: "price",
        type: "uint256",
      },
      {
        name: "mileage",
        type: "uint256",
      },
    ],
    name: "bid",
    outputs: [
      {
        name: "biddingId",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "seller",
        type: "address",
      },
      {
        name: "metaverseId",
        type: "uint256",
      },
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
      },
    ],
    name: "canCreateAuction",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
    ],
    name: "auctionsCount",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "user",
        type: "address",
      },
    ],
    name: "nonce",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "item",
        type: "address",
      },
      {
        name: "index",
        type: "uint256",
      },
    ],
    name: "onAuctions",
    outputs: [
      {
        name: "auctionVerificationID",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "bidder",
        type: "address",
      },
      {
        name: "price",
        type: "uint256",
      },
      {
        name: "auctionVerificationID",
        type: "bytes32",
      },
    ],
    name: "canBid",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "auctionVerificationID",
        type: "bytes32",
      },
    ],
    name: "claim",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "auctionVerificationID",
        type: "bytes32",
      },
    ],
    name: "getAuctionInfo",
    outputs: [
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
      {
        name: "auctionId",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "item",
        type: "address",
      },
    ],
    name: "onAuctionsCount",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "metaverseId",
        type: "uint256",
      },
      {
        name: "index",
        type: "uint256",
      },
    ],
    name: "auctionsOnMetaverse",
    outputs: [
      {
        name: "auctionVerificationID",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
      {
        name: "auctionId",
        type: "uint256",
      },
    ],
    name: "auctions",
    outputs: [
      {
        name: "seller",
        type: "address",
      },
      {
        name: "metaverseId",
        type: "uint256",
      },
      {
        name: "_item",
        type: "address",
      },
      {
        name: "_id",
        type: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
      },
      {
        name: "startTotalPrice",
        type: "uint256",
      },
      {
        name: "endBlock",
        type: "uint256",
      },
      {
        name: "verificationID",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "bidder",
        type: "address",
      },
      {
        name: "index",
        type: "uint256",
      },
    ],
    name: "userBiddingInfo",
    outputs: [
      {
        name: "auctionVerificationID",
        type: "bytes32",
      },
      {
        name: "biddingId",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "commonData",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        name: "seller",
        type: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        name: "startPrice",
        type: "uint256",
      },
      {
        indexed: false,
        name: "endBlock",
        type: "uint256",
      },
      {
        indexed: true,
        name: "auctionVerificationID",
        type: "bytes32",
      },
    ],
    name: "CreateAuction",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: true,
        name: "auctionVerificationID",
        type: "bytes32",
      },
    ],
    name: "CancelAuction",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        name: "bidder",
        type: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        name: "price",
        type: "uint256",
      },
      {
        indexed: true,
        name: "auctionVerificationID",
        type: "bytes32",
      },
      {
        indexed: false,
        name: "biddingId",
        type: "uint256",
      },
    ],
    name: "Bid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        name: "bestBidder",
        type: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        name: "price",
        type: "uint256",
      },
      {
        indexed: true,
        name: "auctionVerificationID",
        type: "bytes32",
      },
      {
        indexed: false,
        name: "biddingId",
        type: "uint256",
      },
    ],
    name: "Claim",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: true,
        name: "auctionVerificationID",
        type: "bytes32",
      },
    ],
    name: "CancelAuctionByOwner",
    type: "event",
  },
];
