/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IItemStoreSale } from "../IItemStoreSale";

export class IItemStoreSale__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IItemStoreSale {
    return new Contract(address, _abi, signerOrProvider) as IItemStoreSale;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "item",
        type: "address",
      },
    ],
    name: "onSalesCount",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "saleVerificationIDs",
        type: "bytes32[]",
      },
    ],
    name: "cancelSale",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "offerVerificationID",
        type: "bytes32",
      },
      {
        name: "amount",
        type: "uint256",
      },
    ],
    name: "acceptOffer",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "metaverseId",
        type: "uint256",
      },
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
      },
      {
        name: "unitPrice",
        type: "uint256",
      },
      {
        name: "partialBuying",
        type: "bool",
      },
      {
        name: "mileage",
        type: "uint256",
      },
    ],
    name: "makeOffer",
    outputs: [
      {
        name: "offerId",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "offeror",
        type: "address",
      },
      {
        name: "metaverseId",
        type: "uint256",
      },
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
      },
    ],
    name: "canOffer",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "offeror",
        type: "address",
      },
      {
        name: "index",
        type: "uint256",
      },
    ],
    name: "userOfferInfo",
    outputs: [
      {
        name: "offerVerificationID",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "seller",
        type: "address",
      },
    ],
    name: "userSellInfoLength",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "metaverseIds",
        type: "uint256[]",
      },
      {
        name: "items",
        type: "address[]",
      },
      {
        name: "ids",
        type: "uint256[]",
      },
      {
        name: "amounts",
        type: "uint256[]",
      },
      {
        name: "unitPrices",
        type: "uint256[]",
      },
      {
        name: "partialBuyings",
        type: "bool[]",
      },
    ],
    name: "sell",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "seller",
        type: "address",
      },
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
    ],
    name: "userOnSaleAmounts",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "user",
        type: "address",
      },
    ],
    name: "nonce",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "saleVerificationIDs",
        type: "bytes32[]",
      },
      {
        name: "amounts",
        type: "uint256[]",
      },
      {
        name: "unitPrices",
        type: "uint256[]",
      },
      {
        name: "mileages",
        type: "uint256[]",
      },
    ],
    name: "buy",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
      {
        name: "saleId",
        type: "uint256",
      },
    ],
    name: "sales",
    outputs: [
      {
        name: "seller",
        type: "address",
      },
      {
        name: "metaverseId",
        type: "uint256",
      },
      {
        name: "_item",
        type: "address",
      },
      {
        name: "_id",
        type: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
      },
      {
        name: "unitPrice",
        type: "uint256",
      },
      {
        name: "partialBuying",
        type: "bool",
      },
      {
        name: "verificationID",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "saleVerificationIDs",
        type: "bytes32[]",
      },
      {
        name: "unitPrices",
        type: "uint256[]",
      },
    ],
    name: "changeSellPrice",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "saleVerificationID",
        type: "bytes32",
      },
    ],
    name: "getSaleInfo",
    outputs: [
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
      {
        name: "saleId",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "offeror",
        type: "address",
      },
    ],
    name: "userOfferInfoLength",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
    ],
    name: "offersCount",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "seller",
        type: "address",
      },
      {
        name: "index",
        type: "uint256",
      },
    ],
    name: "userSellInfo",
    outputs: [
      {
        name: "saleVerificationID",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "metaverseId",
        type: "uint256",
      },
    ],
    name: "salesOnMetaverseLength",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "item",
        type: "address",
      },
      {
        name: "index",
        type: "uint256",
      },
    ],
    name: "onSales",
    outputs: [
      {
        name: "saleVerificationID",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "offerVerificationID",
        type: "bytes32",
      },
    ],
    name: "getOfferInfo",
    outputs: [
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
      {
        name: "offerId",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "seller",
        type: "address",
      },
      {
        name: "metaverseId",
        type: "uint256",
      },
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
      },
    ],
    name: "canSell",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
      {
        name: "offerId",
        type: "uint256",
      },
    ],
    name: "offers",
    outputs: [
      {
        name: "offeror",
        type: "address",
      },
      {
        name: "metaverseId",
        type: "uint256",
      },
      {
        name: "_item",
        type: "address",
      },
      {
        name: "_id",
        type: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
      },
      {
        name: "unitPrice",
        type: "uint256",
      },
      {
        name: "partialBuying",
        type: "bool",
      },
      {
        name: "mileage",
        type: "uint256",
      },
      {
        name: "verificationID",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "commonData",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "item",
        type: "address",
      },
      {
        name: "id",
        type: "uint256",
      },
    ],
    name: "salesCount",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "offerVerificationID",
        type: "bytes32",
      },
    ],
    name: "cancelOffer",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "metaverseId",
        type: "uint256",
      },
      {
        name: "index",
        type: "uint256",
      },
    ],
    name: "salesOnMetaverse",
    outputs: [
      {
        name: "saleVerificationID",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        name: "seller",
        type: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        name: "unitPrice",
        type: "uint256",
      },
      {
        indexed: false,
        name: "partialBuying",
        type: "bool",
      },
      {
        indexed: true,
        name: "saleVerificationID",
        type: "bytes32",
      },
    ],
    name: "Sell",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        name: "newUnitPrice",
        type: "uint256",
      },
      {
        indexed: true,
        name: "saleVerificationID",
        type: "bytes32",
      },
    ],
    name: "ChangeSellPrice",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        name: "buyer",
        type: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        name: "isFulfilled",
        type: "bool",
      },
      {
        indexed: true,
        name: "saleVerificationID",
        type: "bytes32",
      },
    ],
    name: "Buy",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        name: "saleVerificationID",
        type: "bytes32",
      },
    ],
    name: "CancelSale",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        name: "offeror",
        type: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        name: "unitPrice",
        type: "uint256",
      },
      {
        indexed: false,
        name: "partialBuying",
        type: "bool",
      },
      {
        indexed: true,
        name: "offerVerificationID",
        type: "bytes32",
      },
    ],
    name: "MakeOffer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        name: "offerVerificationID",
        type: "bytes32",
      },
    ],
    name: "CancelOffer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        name: "acceptor",
        type: "address",
      },
      {
        indexed: false,
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        name: "isFulfilled",
        type: "bool",
      },
      {
        indexed: true,
        name: "offerVerificationID",
        type: "bytes32",
      },
    ],
    name: "AcceptOffer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: true,
        name: "saleVerificationID",
        type: "bytes32",
      },
    ],
    name: "CancelSaleByOwner",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "metaverseId",
        type: "uint256",
      },
      {
        indexed: true,
        name: "item",
        type: "address",
      },
      {
        indexed: false,
        name: "id",
        type: "uint256",
      },
      {
        indexed: true,
        name: "offerVerificationID",
        type: "bytes32",
      },
    ],
    name: "CancelOfferByOwner",
    type: "event",
  },
];
