/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ITurntableKIP17ListenersInterface extends ethers.utils.Interface {
  functions: {
    "shares(uint256,uint256)": FunctionFragment;
    "claimableOf(uint256,uint256)": FunctionFragment;
    "unlisten(uint256,uint256[])": FunctionFragment;
    "accumulativeOf(uint256,uint256)": FunctionFragment;
    "listenerCount(uint256)": FunctionFragment;
    "claim(uint256,uint256[])": FunctionFragment;
    "listen(uint256,uint256[])": FunctionFragment;
    "listeners(uint256,uint256)": FunctionFragment;
    "realClaimedOf(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "shares",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableOf",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlisten",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "accumulativeOf",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listenerCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "listen",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "listeners",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "realClaimedOf",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "shares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimableOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlisten", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accumulativeOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listenerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listen", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listeners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "realClaimedOf",
    data: BytesLike
  ): Result;

  events: {
    "Distribute(address,uint256)": EventFragment;
    "Claim(uint256,uint256,uint256)": EventFragment;
    "Listen(uint256,address,uint256)": EventFragment;
    "Unlisten(uint256,address,uint256)": EventFragment;
    "SetTurntableFee(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Distribute"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Listen"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unlisten"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetTurntableFee"): EventFragment;
}

export type DistributeEvent = TypedEvent<
  [string, BigNumber] & { by: string; distributed: BigNumber }
>;

export type ClaimEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber] & {
    turntableId: BigNumber;
    id: BigNumber;
    claimed: BigNumber;
  }
>;

export type ListenEvent = TypedEvent<
  [BigNumber, string, BigNumber] & {
    turntableId: BigNumber;
    owner: string;
    id: BigNumber;
  }
>;

export type UnlistenEvent = TypedEvent<
  [BigNumber, string, BigNumber] & {
    turntableId: BigNumber;
    owner: string;
    id: BigNumber;
  }
>;

export type SetTurntableFeeEvent = TypedEvent<[BigNumber] & { fee: BigNumber }>;

export class ITurntableKIP17Listeners extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ITurntableKIP17ListenersInterface;

  functions: {
    shares(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    claimableOf(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    unlisten(
      turntableId: BigNumberish,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    accumulativeOf(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    listenerCount(
      turntableId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    claim(
      turntableId: BigNumberish,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    listen(
      turntableId: BigNumberish,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    listeners(
      turntableId: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    realClaimedOf(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  shares(
    turntableId: BigNumberish,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claimableOf(
    turntableId: BigNumberish,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  unlisten(
    turntableId: BigNumberish,
    ids: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  accumulativeOf(
    turntableId: BigNumberish,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  listenerCount(
    turntableId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claim(
    turntableId: BigNumberish,
    ids: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  listen(
    turntableId: BigNumberish,
    ids: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  listeners(
    turntableId: BigNumberish,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  realClaimedOf(
    turntableId: BigNumberish,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    shares(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimableOf(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unlisten(
      turntableId: BigNumberish,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    accumulativeOf(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listenerCount(
      turntableId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(
      turntableId: BigNumberish,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    listen(
      turntableId: BigNumberish,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    listeners(
      turntableId: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    realClaimedOf(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "Distribute(address,uint256)"(
      by?: string | null,
      distributed?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { by: string; distributed: BigNumber }
    >;

    Distribute(
      by?: string | null,
      distributed?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { by: string; distributed: BigNumber }
    >;

    "Claim(uint256,uint256,uint256)"(
      turntableId?: BigNumberish | null,
      id?: BigNumberish | null,
      claimed?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      { turntableId: BigNumber; id: BigNumber; claimed: BigNumber }
    >;

    Claim(
      turntableId?: BigNumberish | null,
      id?: BigNumberish | null,
      claimed?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      { turntableId: BigNumber; id: BigNumber; claimed: BigNumber }
    >;

    "Listen(uint256,address,uint256)"(
      turntableId?: BigNumberish | null,
      owner?: string | null,
      id?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { turntableId: BigNumber; owner: string; id: BigNumber }
    >;

    Listen(
      turntableId?: BigNumberish | null,
      owner?: string | null,
      id?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { turntableId: BigNumber; owner: string; id: BigNumber }
    >;

    "Unlisten(uint256,address,uint256)"(
      turntableId?: BigNumberish | null,
      owner?: string | null,
      id?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { turntableId: BigNumber; owner: string; id: BigNumber }
    >;

    Unlisten(
      turntableId?: BigNumberish | null,
      owner?: string | null,
      id?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { turntableId: BigNumber; owner: string; id: BigNumber }
    >;

    "SetTurntableFee(uint256)"(
      fee?: null
    ): TypedEventFilter<[BigNumber], { fee: BigNumber }>;

    SetTurntableFee(
      fee?: null
    ): TypedEventFilter<[BigNumber], { fee: BigNumber }>;
  };

  estimateGas: {
    shares(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimableOf(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unlisten(
      turntableId: BigNumberish,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    accumulativeOf(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listenerCount(
      turntableId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(
      turntableId: BigNumberish,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    listen(
      turntableId: BigNumberish,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    listeners(
      turntableId: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    realClaimedOf(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    shares(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimableOf(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unlisten(
      turntableId: BigNumberish,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    accumulativeOf(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listenerCount(
      turntableId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(
      turntableId: BigNumberish,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    listen(
      turntableId: BigNumberish,
      ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    listeners(
      turntableId: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    realClaimedOf(
      turntableId: BigNumberish,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
